# Generated by Django 4.0.5 on 2022-06-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exist_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDevice',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exist_devices.device', verbose_name='Device')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone number')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Height of device (sm)')),
                ('height_conf', models.IntegerField(blank=True, default=0, verbose_name='Height conf (sm)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Latitude of location')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Longitude of location')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channeldevices', to=settings.AUTH_USER_MODEL, verbose_name='Belong to')),
            ],
            options={
                'verbose_name': 'Channel device',
                'verbose_name_plural': 'Channel devices',
            },
        ),
    ]
