# Generated by Django 4.0.6 on 2022-07-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exist_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDevice',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exist_devices.device', verbose_name='Device')),
                ('ministry_id', models.CharField(blank=True, max_length=20, verbose_name='Ministry ID')),
                ('permission_to_send', models.BooleanField(default=False, verbose_name='Permission to send data')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone number')),
                ('full_height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Full height (sm)')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Height of water (sm)')),
                ('height_conf', models.IntegerField(blank=True, default=0, verbose_name='Height conf (sm)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude of location')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude of location')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_devices', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channeldevices', to=settings.AUTH_USER_MODEL, verbose_name='Belong to')),
            ],
            options={
                'verbose_name': 'Channel device',
                'verbose_name_plural': 'Channel devices',
            },
        ),
        migrations.CreateModel(
            name='ChannelMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude of location')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude of location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channeldevice', verbose_name='Channel device')),
            ],
            options={
                'verbose_name': 'Channel movement message',
                'verbose_name_plural': 'Channels movement messages',
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('h', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='From device to water (sm)')),
                ('water_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume of water (cubic meters/sec)')),
                ('bat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Battery power (volt)')),
                ('is_charging', models.BooleanField(blank=True, null=True, verbose_name='Is charging')),
                ('net', models.SmallIntegerField(verbose_name='Network quality')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channeldevice', verbose_name='Channel device')),
            ],
            options={
                'verbose_name': 'Channel message',
                'verbose_name_plural': 'Channels messages',
            },
        ),
        migrations.CreateModel(
            name='ChannelDeviceVolumeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tens', models.IntegerField(default=0, verbose_name='Tens')),
                ('zero', models.FloatField(default=0, verbose_name='0')),
                ('one', models.FloatField(default=0, verbose_name='1')),
                ('two', models.FloatField(default=0, verbose_name='2')),
                ('three', models.FloatField(default=0, verbose_name='3')),
                ('four', models.FloatField(default=0, verbose_name='4')),
                ('five', models.FloatField(default=0, verbose_name='5')),
                ('six', models.FloatField(default=0, verbose_name='6')),
                ('seven', models.FloatField(default=0, verbose_name='7')),
                ('eight', models.FloatField(default=0, verbose_name='8')),
                ('nine', models.FloatField(default=0, verbose_name='9')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channeldevice', verbose_name='Device')),
            ],
        ),
    ]
