# Generated by Django 4.0.5 on 2022-06-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exist_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDevice',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exist_devices.device', verbose_name='Device')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone number')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Height of device (sm)')),
                ('height_conf', models.IntegerField(blank=True, default=0, verbose_name='Height conf (sm)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude of location')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude of location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channeldevices', to=settings.AUTH_USER_MODEL, verbose_name='Belong to')),
            ],
            options={
                'verbose_name': 'Channel device',
                'verbose_name_plural': 'Channel devices',
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='H1 (sm)')),
                ('h2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='H2 (sm)')),
                ('w1', models.IntegerField(verbose_name='W1 (liter/sec)')),
                ('w2', models.IntegerField(verbose_name='W2 (cubic meters/hour)')),
                ('vol', models.BigIntegerField(verbose_name='Total amount of water')),
                ('bat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Battery power (volt)')),
                ('net', models.SmallIntegerField(verbose_name='Network quality')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('channel_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channeldevice', verbose_name='Channel device')),
            ],
            options={
                'verbose_name': 'Channel message',
                'verbose_name_plural': 'Channels messages',
            },
        ),
    ]
