# Generated by Django 4.0.5 on 2022-06-27 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeldevice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channeldevices', to=settings.AUTH_USER_MODEL, verbose_name='Belong to'),
        ),
    ]
