# Generated by Django 4.0.5 on 2022-06-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channeldevice_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='H1 (sm)')),
                ('h2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='H2 (sm)')),
                ('w1', models.IntegerField(verbose_name='Amount of water (liter/sec)')),
                ('w2', models.IntegerField(verbose_name='Amount of water (cubic meters/hour')),
                ('vol', models.BigIntegerField(verbose_name='Total amount of water')),
                ('bat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Battery power (volt)')),
                ('net', models.SmallIntegerField(verbose_name='Network quality')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('channel_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channeldevice', verbose_name='Channel device')),
            ],
            options={
                'verbose_name': 'Channel message',
                'verbose_name_plural': 'Channels messages',
            },
        ),
    ]
