# Generated by Django 4.0.5 on 2022-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channelmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='w1',
            field=models.IntegerField(verbose_name='W1 (liter/sec)'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='w2',
            field=models.IntegerField(verbose_name='W2 (cubic meters/hour)'),
        ),
    ]
