# Generated by Django 4.0.5 on 2022-07-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channeldevice_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDeviceVolumeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tens', models.IntegerField()),
                ('ones', models.IntegerField()),
                ('value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channeldevice')),
            ],
        ),
    ]
