# Generated by Django 4.0.6 on 2022-07-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channeldevicevolumetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeldevice',
            old_name='channels_master',
            new_name='master',
        ),
    ]
