# Generated by Django 4.0.6 on 2022-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_rename_channels_master_channeldevice_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeldevicevolumetable',
            name='ones',
        ),
        migrations.RemoveField(
            model_name='channeldevicevolumetable',
            name='value',
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channeldevicevolumetable',
            name='_9',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='tens',
            field=models.IntegerField(default=0),
        ),
    ]
