# Generated by Django 4.0.6 on 2022-07-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_channeldevicevolumetable__7'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_0',
            new_name='eight',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_1',
            new_name='five',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_2',
            new_name='four',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_3',
            new_name='nine',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_4',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_5',
            new_name='seven',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_6',
            new_name='six',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_7',
            new_name='three',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_8',
            new_name='two',
        ),
        migrations.RenameField(
            model_name='channeldevicevolumetable',
            old_name='_9',
            new_name='zero',
        ),
    ]
