# Generated by Django 4.0.6 on 2022-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_rename__0_channeldevicevolumetable_eight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='channel_device',
            new_name='device',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='vol',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='w1',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='w2',
        ),
        migrations.AddField(
            model_name='channeldevice',
            name='full_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Full height (sm)'),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='From device to water (sm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='water_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume of water (cubic meters/sec)'),
        ),
    ]
