# Generated by Django 4.0.6 on 2022-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_rename_channel_device_channelmessage_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='is_charging',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is charging'),
        ),
    ]
