# Generated by Django 4.0.6 on 2022-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_channelmessage_is_charging'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldevice',
            name='ministry_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ministry ID'),
        ),
        migrations.AddField(
            model_name='channeldevice',
            name='permission_to_send',
            field=models.BooleanField(default=False, verbose_name='Permission to send data'),
        ),
        migrations.AlterField(
            model_name='channeldevice',
            name='full_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Full height (sm)'),
        ),
    ]
