# Generated by Django 4.0.6 on 2022-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_channeldevice_ministry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Full path to send json')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date and time')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added date and time')),
            ],
            options={
                'verbose_name': 'Ministry link',
                'verbose_name_plural': 'Ministry links',
            },
        ),
    ]
