# Generated by Django 4.0.6 on 2022-07-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0013_ministrylink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinistryLink',
        ),
    ]
