# Generated by Django 4.0.6 on 2022-07-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_delete_ministrylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channeldevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='eight',
            field=models.FloatField(default=0, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='five',
            field=models.FloatField(default=0, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='four',
            field=models.FloatField(default=0, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='nine',
            field=models.FloatField(default=0, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='one',
            field=models.FloatField(default=0, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='seven',
            field=models.FloatField(default=0, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='six',
            field=models.FloatField(default=0, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='tens',
            field=models.IntegerField(default=0, verbose_name='Tens'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='three',
            field=models.FloatField(default=0, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='two',
            field=models.FloatField(default=0, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='channeldevicevolumetable',
            name='zero',
            field=models.FloatField(default=0, verbose_name='0'),
        ),
    ]
