# Generated by Django 4.0.6 on 2022-07-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welldevice',
            options={'verbose_name': 'Well device', 'verbose_name_plural': 'Wells devices'},
        ),
        migrations.CreateModel(
            name='WellDeviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Water height (sm)')),
                ('mineral', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mineral (gramm/liter)')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature (Celsius)')),
                ('bat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Battery power (volt)')),
                ('is_charging', models.BooleanField(blank=True, null=True, verbose_name='Is charging')),
                ('net', models.SmallIntegerField(verbose_name='Network quality')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wells.welldevice', verbose_name='Well device')),
            ],
            options={
                'verbose_name': 'Well message',
                'verbose_name_plural': 'Wells messages',
            },
        ),
    ]
